version: '3'
services:
    mysql57:
        image: mysql:5.7
        restart: unless-stopped
        container_name: mysql57-container
        ports:
            - "127.0.0.1:33306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: soapbox
            MYSQL_DATABASE: soapbox
        volumes:
            - soapbox-mysql57-data:/var/lib/mysql
volumes:
    soapbox-mysql57-data:            